---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-acc1
  namespace: account-1
  labels:
    app: alpine-acc1
#  annotations:                                          
#    opflex.cisco.com/endpoint-group: '{"tenant":"OSP_TENANT","app-profile":"ACCOUNT_1","name":"ACCOUNT_1"}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-acc1
  template:
    metadata:
      labels:
        app: alpine-acc1
    spec:
      containers:
      - name: alpine-acc1
        image: alpine:latest
        command: ["ping", "127.0.0.1"]
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30